# Generated by Django 5.0.7 on 2024-07-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_history_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='main',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
